import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TheHeaderComponent from "@/components/TheHeader";
import { Tooltip } from "@mui/material";
import BackButton from "@/components/BackButton";
import TheFooterComponent from "@/components/TheFooter";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <TheHeaderComponent />
        </header>

        <div className="mt-[15vh] mb-[5vh] h-auto mx-6">{children}</div>

        <footer>
          <div className="fixed bottom-[5rem] right-3 z-50">
            <Tooltip title="Back to top">
              <BackButton />
            </Tooltip>
          </div>

          <TheFooterComponent />
        </footer>
      </body>
    </html>
  );
}
