import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TheHeaderComponent from "@/components/TheHeader";
import { Tooltip } from "@mui/material";
import BackButton from "@/components/BackButton";
import TheFooterComponent from "@/components/TheFooter";
import React from "react";
import "./globals.css";
import "../shared/assets/styles/button.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <TheHeaderComponent />
        </header>

        <div className="mt-[12vh] py-4 h-auto mx-6 z-50">{children}</div>

        <footer className="w-full z-50">
          <div className="hidden md:block fixed bottom-[6rem] right-3">
            <Tooltip title="Back to top">
              <BackButton />
            </Tooltip>
          </div>

          <div>
            <TheFooterComponent />
          </div>
        </footer>
      </body>
    </html>
  );
}
